contrib: fedora.dev update to f36
Updated dockerfile to Fedora 36 and added missing
package for the build.

error: Failed build dependencies:
        desktop-file-utils is needed by openvswitch-2.17.90-1.fc36.x86_64
make: *** [Makefile:7285: rpm-fedora] Error 11

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>