hack/lint.sh: Use full image tag
When using podman, `make lint` fails due to the following error:
Error: short-name resolution enforced but cannot prompt without a TTY
make: *** [Makefile:93: lint] Error 125

Root cause is podman wont add docker.io registry name by default.

Use full image name including the registry to aviod failures on envs
that use podman.

Signed-off-by: Or Mergi <ormergi@redhat.com>