Update and cleanup older stale ACLs upon startup
This PR does two things:

1) Loops through all the ACLs that have `ARPallowPolicy`
in their names and have " && arp" in their match expression
and deletes it. This is because we did
https://github.com/openshift/ovn-kubernetes/pull/1043/files where
we changed the match but didn't remove acls on the older match which
causes problems like:

2022-06-01T08:17:44.635401164Z E0601 08:17:44.634509       1 ovn.go:753]
Failed to create network policy mdh-old/allow-from-other-namespaces,
error: failed to create default port groups and acls for policy:
mdh-old/allow-from-other-namespaces, error: unexpectedly found multiple
equivalent ACLs: [{UUID:3bc36c0e-ee1a-4609-a240-c211f14f379b
Action:allow Direction:to-lport
ExternalIDs:map[default-deny-policy-type:Ingress] Label:0 Log:false
Match:outport == @a13985064446031893020_ingressDefaultDeny && arp
Meter:0xc003245210 Name:0xc003245220 Options:map[] Priority:1001
Severity:0xc003245230} {UUID:41702278-fb49-4418-abca-6425912d1e63
Action:allow Direction:to-lport
ExternalIDs:map[default-deny-policy-type:Ingress] Label:0 Log:false
Match:outport == @a13985064446031893020_ingressDefaultDeny && (arp ||
nd) Meter:0xc0032452a0 Name:0xc0032452b0 Options:map[] Priority:1001
Severity:0xc0032452c0}]

on upgrades

2) When we create the default deny ACLs for a namespace with at least
one network policy, we name it "namespace_np-name". This doesn't make
sense since the ACL is applicable to all the network policies in that
namespace. The policy that get's created first becomes the lucky winner.
This PR updates the names of default deny ACLs to
"namespace_egressDefaultDeny" OR "namespace_ingressDefaultDeny" so that
"we can stop being stupid" :) and stop errors like:

2022-06-09T17:15:00.952174381Z E0609 17:15:00.952154       1 ovn.go:753]
Failed to create network policy oit-ssi-fluentd/fluentd-input, error:
failed to create default port groups and acls for policy:
oit-ssi-fluentd/fluentd-input, error: unexpectedly found multiple
equivalent ACLs: [{UUID:5b98f17d-789f-4de1-9beb-36741bfa40d1 Action:drop
Direction:from-lport ExternalIDs:map[default-deny-policy-type:Egress]
Label:0 Log:false Match:inport ==
@a12933912868060780448_egressDefaultDeny Meter:0xc001388aa0
Name:0xc001388ab0 Options:map[apply-after-lb:true] Priority:1000
Severity:0xc001388ac0} {UUID:b9349cb8-99b0-4130-92cf-ab11b4874a11
Action:drop Direction:from-lport
ExternalIDs:map[default-deny-policy-type:Egress] Label:0 Log:false
Match:inport == @a12933912868060780448_egressDefaultDeny
Meter:0xc001388c90 Name:0xc001388ca0 Options:map[apply-after-lb:true]
Priority:1000 Severity:0xc001388cb0}]

(NOTE: not sure how the user ended up with two default ACLs in the same
namespace, but they did!)

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>